# Generated by Django 5.2.7 on 2025-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('Location', models.CharField(max_length=150)),
                ('Timeopen', models.TimeField(blank=True, null=True)),
                ('Closetime', models.TimeField(blank=True, null=True)),
                ('image', models.URLField(blank=True)),
                ('city', models.CharField(max_length=30)),
                ('Isopen', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('deliverytime', models.FloatField(default=30)),
            ],
        ),
    ]
