# Generated by Django 5.2.7 on 2025-12-02 17:30

import partner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_restaurants_options_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100, validators=[partner.models.passwordcheck])),
                ('confirmpass', models.CharField(max_length=100)),
            ],
        ),
    ]
