# Generated by Django 5.2.7 on 2025-12-08 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partnersignup_username_alter_restaurants_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Cuisenetypes',
            field=models.CharField(blank=True, default='Indian,Chinese', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='Restauranttype',
            field=models.CharField(blank=True, choices=[('veg', 'veg'), ('nonveg', 'nonveg'), ('both', 'both')], default='both', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Closetime',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Timeopen',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='deliverytime',
            field=models.FloatField(blank=True, default=30, null=True),
        ),
    ]
