# Generated by Django 5.2.7 on 2025-12-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_restaurants_cuisenetypes_restaurants_restauranttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partnersignup'),
        ),
    ]
