# Generated by Django 5.2.7 on 2025-12-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_restaurants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='USER', to='partner.partnersignup'),
        ),
    ]
