# Generated by Django 5.2.7 on 2025-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_alter_item_category_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
