# Generated by Django 5.2.7 on 2026-01-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
