# Generated by Django 5.2.7 on 2026-01-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
