# Generated by Django 5.2.7 on 2025-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cart_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='add',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
