# Generated by Django 5.2.7 on 2025-12-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cart_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='add',
        ),
    ]
