# Generated by Django 5.2.7 on 2026-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('Flat', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=100)),
            ],
        ),
    ]
